### ISSUE TITLE
Design Docs Feedback: Sample State, Backend & Frontend Routes

### ISSUE THREAD

**Issue by RosemaryGonzaga** [ParaLogia/discrud#2]
DESIGN DOCS FEEDBACK - Sample State:

1. General
   - [x] Convert key names to camelCase, in keeping with JavaScript naming conventions
2. Servers
   - [x] As mentioned in the schema feedback, each server should have an invitation_link; include a key of `invitationLink` in your servers slice of state.
   - [x] You’ll also want an easy reference to all the users that are on the server, so a `userIds` key will be useful.
3. Users
   - [x] Include an `imageUrl` for storing a reference to each user’s profile avatar.

DESIGN DOCS FEEDBACK - Backend Routes:

   - Your notes are on point and very well considered. I agree you shouldn’t need nested `GET` routes for channels or messages. Sending up the associated channels in response to a request for a single server is more efficient than requiring multiple responses to get all the necessary info when switching servers.

DESIGN DOCS FEEDBACK - Frontend Routes:

   - Great work! I can’t think of any tweaks to make. My only question is to clarify - the ChannelShow is essentially a MessageIndex, is that correct?

**Comment by ParaLogia** [comment]
We can talk about these when we meet individually:

1. I updated the state keys to camelCase. Since the columns are currently stored as snake_case, at what point should the conversion be done?
    - Backend
      - schema (no conversion; always camelCase)
      - jbuilder views (I'm learning toward this one)
    - Frontend
      - API Utils
      - action creators
      - reducers
    - Other

2. I added `imageUrl`s to the `users` state. Should I add these to the schema as well? Is this where AWS storage is going to come into play?

3. Yes, ChannelShow is essentially a MessageIndex
